PostgreSQL:
  restart: always
  image: postgres:latest
  ports:
    - "5432:5432"
  environment:
    - DEBUG=false

    - DB_USER=
    - DB_PASS=
    - DB_NAME=
    - DB_TEMPLATE=

    - DB_EXTENSION=

    - REPLICATION_MODE=
    - REPLICATION_USER=
    - REPLICATION_PASS=
    - REPLICATION_SSLMODE=
  volumes:
    - /home/capcolabs/data/psql/data:/var/lib/postgresql